USE [master]
GO
/****** Object:  Database [QLS]    Script Date: 04/05/2024 9:53:07 CH ******/
CREATE DATABASE [QLS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\QLS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\QLS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QLS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLS] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QLS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLS] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QLS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLS] SET RECOVERY FULL 
GO
ALTER DATABASE [QLS] SET  MULTI_USER 
GO
ALTER DATABASE [QLS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'QLS', N'ON'
GO
ALTER DATABASE [QLS] SET QUERY_STORE = ON
GO
ALTER DATABASE [QLS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QLS]
GO
/****** Object:  Table [dbo].[NHAXUATBAN]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAXUATBAN](
	[MaNXB] [int] NOT NULL,
	[TenNXB] [nvarchar](30) NULL,
	[DiaChi] [nvarchar](50) NULL,
	[SDT] [nvarchar](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNXB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SACH]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SACH](
	[Masach] [nvarchar](10) NOT NULL,
	[Tieude] [nvarchar](50) NULL,
	[Dongia] [int] NULL,
	[Soluong] [int] NULL,
	[MaNXB] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Masach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Masach] UNIQUE NONCLUSTERED 
(
	[Masach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[v_Sach1]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[v_Sach1]
as
SELECT SACH.Masach as 'Mã sách', SACH.Tieude, SACH.Dongia, SACH.Soluong, NHAXUATBAN.TenNXB, SACH.MaNXB
FROM SACH inner join NHAXUATBAN on SACH.MaNXB=NHAXUATBAN.MaNXB
GO
/****** Object:  StoredProcedure [dbo].[searchByIndex]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[searchByIndex]
@ma nvarchar(10)
as
begin
select * from v_Sach1
where [Mã sách]=@ma
end
GO
/****** Object:  StoredProcedure [dbo].[searchbyMoney]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[searchbyMoney]
    @from int,
	@to int
AS
begin
select * from v_Sach1
WHERE Dongia>@from and Dongia<@to
end
GO
/****** Object:  StoredProcedure [dbo].[searchName]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[searchName]
    @tieude NVARCHAR(50)
AS
begin
select * from v_Sach1
WHERE Tieude like @tieude
end
GO
/****** Object:  StoredProcedure [dbo].[suaSach]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[suaSach]
    @masach NVARCHAR(10),
    @tieude NVARCHAR(50),
    @dongia INT,
    @soluong INT,
    @manxhb INT
AS
begin
UPDATE SACH
SET Tieude=@tieude , Dongia=@dongia, Soluong=@soluong, MaNXB=@manxhb 
where @masach=Masach
end
GO
/****** Object:  StoredProcedure [dbo].[themSach]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[themSach]
    @masach NVARCHAR(10),
    @tieude NVARCHAR(50),
    @dongia INT,
    @soluong INT,
    @manxhb INT
AS
BEGIN
    INSERT INTO SACH VALUES (@masach, @tieude, @dongia, @soluong, @manxhb);
END
GO
/****** Object:  StoredProcedure [dbo].[xoaSach]    Script Date: 04/05/2024 9:53:07 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[xoaSach]
    @masach NVARCHAR(10)
AS
BEGIN
    delete from SACH where SACH.Masach=@masach
end
GO
USE [master]
GO
ALTER DATABASE [QLS] SET  READ_WRITE 
GO
